version: '3'
services:
  api:
    container_name: library-api
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - mysql-db
    links:
      - mysql-db
  mysql-db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
